### ISSUE TITLE
Masłowski każe mieć na poniedziałek a my nic nie mamy zrobione

### ISSUE THREAD

**Issue by Lachcim** [cerber-os/lo3-chmura#1]
- NA POMOC
- - NA POMOC
- - - NA POMOC
- - - - NA POMOC
- - - - - NA POMOC
- - - - - - NA POMOC
- - - - - - - NA POMOC
- - - - - - - - NA POMOC
- - - - - - - - - NA POMOC
- - - - - - - - - - NA POMOC

**Comment by cerber-os** [comment]
Nie mamy interfejsu, ale wnętrze śmiga.

**Comment by Lachcim** [comment]
W takim razie assignuję front end developera

**Comment by cerber-os** [comment]
Cytując: "DO ROBOTY!!!"

**Comment by Lachcim** [comment]
Mamy coś zrobione, zamykam
